ALTER TYPE "MembershipTier" ADD VALUE IF NOT EXISTS 'BASIC';
ALTER TYPE "CommissionType" ADD VALUE IF NOT EXISTS 'SPONSOR_BONUS';
ALTER TYPE "CommissionType" ADD VALUE IF NOT EXISTS 'REWARD_BONUS';
ALTER TYPE "CommissionType" ADD VALUE IF NOT EXISTS 'PROFIT_SHARING_BONUS';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'REGISTRATION_BONUS';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'SPONSOR_BONUS';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'LEVEL_BONUS';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'REWARD_BONUS';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'PROFIT_SHARING_BONUS';

ALTER TABLE "memberships" DROP CONSTRAINT IF EXISTS "memberships_active_levels_check";
ALTER TABLE "memberships"
  ADD CONSTRAINT "memberships_active_levels_check" CHECK ("active_levels" BETWEEN 0 AND 10);
