ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'WITHDRAWAL_REQUEST';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'WITHDRAWAL_REFUND';

ALTER TABLE "withdrawals"
  ADD COLUMN IF NOT EXISTS "fee" DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "final_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "bank_name" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "account_number" VARCHAR(40),
  ADD COLUMN IF NOT EXISTS "account_holder_name" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "approved_by" UUID,
  ADD COLUMN IF NOT EXISTS "approved_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "rejected_by" UUID,
  ADD COLUMN IF NOT EXISTS "rejected_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "notes" TEXT;

UPDATE "withdrawals"
SET "final_amount" = "amount"
WHERE "final_amount" = 0;
